### PR TITLE
Add logging

### PR DESCRIPTION
**Pull request by shjortConcordium**
## Purpose

Add logging

## Changes

Added logging capabilities.
Log errors throughout the app.
Export the logs from the application menu.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Comment by soerenbf** [comment]
Logging for auto updates needs to be changed to use new logging implementation as well.

**Review by soerenbf — APPROVED** [review]
Looks good!

**Comment by orhoj** [comment]
It seems like that the logging does not provide the filename (and perhaps also the line number) of where it was logged from. This is required to make it useful to debug from.

**Comment by orhoj** [comment]
I am a bit uncertain about what to do when logging errors caught in a try-catch, as the object thrown can have any type, so I am not sure if what we have here works in general, or will break down in certain cases?

**Comment by shjortConcordium** [comment]
> I am a bit uncertain about what to do when logging errors caught in a try-catch, as the object thrown can have any type, so I am not sure if what we have here works in general, or will break down in certain cases?

Well we just include the error in the log, so as long as the object is serializable, then it should work perfectly, and otherwise those "non-serializable" details will just not be in the log.

**Pull request merged**
