### PR TITLE
Context isolation

### PR DESCRIPTION
**Pull request by shjortConcordium**
## Purpose

Enable Context Isolation.

## Changes

Enables Context isolation, and moves stuff to preload script.
Communication with database, files and ledger + http and grpc requests are moved to the preload script. 
refactoring of code that use to interface with ipc.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Review by soerenbf — CHANGES_REQUESTED** [review]
Did regression testing on what i could think of being implicated by the changes, and found that I cannot create an identity (at least using the "concordium test" identity provider) on this branch.

Other essential flows seemed to work fine. Tested the following:
- Simple transfer
- Account creation
- Export/import
- Open application page from menu (terms & conditions)
- Change wallet password

**Review by soerenbf — COMMENTED** [review]
On startup I get a warning stating that `webview` bypasses the security gains of contextIsolation mode. So maybe we should look into removing webviews as well in favor of `BrowserView`, as you said yourself 😄

**Comment by shjortConcordium** [comment]
> Did regression testing on what i could think of being implicated by the changes, and found that I cannot create an identity (at least using the "concordium test" identity provider) on this branch.
> 
> Other essential flows seemed to work fine. Tested the following:
> 
>     * Simple transfer
> 
>     * Account creation
> 
>     * Export/import
> 
>     * Open application page from menu (terms & conditions)
> 
>     * Change wallet password

I've fixed it. I had to move the http get request back to the main thread.

> On startup I get a warning stating that `webview` bypasses the security gains of contextIsolation mode. So maybe we should look into removing webviews as well in favor of `BrowserView`, as you said yourself smile

I have disabled the webview tag and used Browserview instead.

**Comment by soerenbf** [comment]
> > On startup I get a warning stating that `webview` bypasses the security gains of contextIsolation mode. So maybe we should look into removing webviews as well in favor of `BrowserView`, as you said yourself :smile:
> 
> I have disabled the webview tag and used Browserview instead.

This seems to work now! 👍

**Review by soerenbf — APPROVED** [review]
Identity issuance now seems to work as expected as well.

**Pull request merged**
