### PR TITLE
about added under help in menu

### PR DESCRIPTION
**Pull request by soerenbf**
## Purpose

On Mac, and generally other applications on windows as well, version is accessible through native menu under about. This PR adds "about" under "help" on windows/linux.

## Changes

- Adds "about" menu point to native application menu for windows/linux

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

Closes #82

### CODE REVIEW

**Comment by shjortConcordium** [comment]
'about' does not do anything, for me, on Linux

**Comment by soerenbf** [comment]
> 'about' does not do anything, for me, on Linux

Did a manual implementation for linux.

**Comment by shjortConcordium** [comment]
> > 'about' does not do anything, for me, on Linux
> 
> Did a manual implementation for Linux.

It looks a little weird, but more importantly it doesn't use the correct version number:
Screenshot from 2021-09-21 10-04-35

Please make sure it uses the correct version on all the platforms.

**Comment by soerenbf** [comment]
> > > 'about' does not do anything, for me, on Linux
> > 
> > 
> > Did a manual implementation for Linux.
> 
> It looks a little weird, but more importantly it doesn't use the correct version number:
> Screenshot from 2021-09-21 10-04-35
> 
> Please make sure it uses the correct version on all the platforms.

Don't know what's up with the size of it.. probably something to do with 4k screens. As for the version, when running dev mode, it uses the electron version. It does this on all platforms, as I get the version by calling `app.getVersion()`, to keep it in line with how version is produced on build.

**Review by shjortConcordium — APPROVED** [review]

**Pull request merged**
